version: "3.9"

services:
  api:
    container_name: micro-orm-example-api
    build: .
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run start:dev
    restart: always
    env_file:
      - .env
    # environment:
    # - DB_HOST:${DB_HOST}
    # - DB_USER=${DB_USER}
    # - DB_PASSWORD=${DB_PASSWORD}
    # - DB_NAME=${DB_NAME}
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis
    container_name: baiku_postgis_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - data:/var/lib/postgresql/data


volumes:
  data:

